### ISSUE TITLE
Uncaught TypeError: plugin.apply is not a function When Running Karma unit test

### ISSUE THREAD

**Issue by achen224** [declandewet/vue-meta#25] opened 2016-11-17 08:27 UTC
Hello,

I've installed the plugin with npm and imported it in my router 

Code:
```
import Vue from 'vue'
import Router from 'vue-router'
import Meta from 'vue-meta'
Vue.use(Router)
Vue.use(Meta)
```

after this, Karma unit test throw error 

Error:
```
17 11 2016 16:17:25.621:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
17 11 2016 16:17:25.625:INFO [launcher]: Launching browser Chrome with unlimited concurrency
17 11 2016 16:17:25.632:INFO [launcher]: Starting browser Chrome
17 11 2016 16:17:26.819:INFO [Chrome 54.0.2840 (Mac OS X 10.12.1)]: Connected on socket /#Dan5pkY-wXijHOQSAAAA with id 65822028
Chrome 54.0.2840 (Mac OS X 10.12.1) ERROR
  Uncaught TypeError: plugin.apply is not a function
  at index.js:3310

Chrome 54.0.2840 (Mac OS X 10.12.1): Executed 0 of 0 ERROR (0.539 secs / 0 secs)
```

Any idea?

Thank's :)

**Comment by declandewet** [comment] 2016-11-17 10:31
Hi @achen224 - thanks for the report.

I've tried reproducing your issue but it works for me. Could you perhaps provide more info?

**Comment by lijiakof** [comment] 2016-11-18 14:47
I use it base on vue 2.0.5，and has the same error.Uncaught TypeError: plugin.apply is not a function(…) vue.common.js:3219

**Comment by declandewet** [comment] 2016-11-18 17:25
@lijiakof are you passing any options to `vue-meta`? can I see some code that depicts how you're using `vue-meta`? would be a big help 👷

**Comment by Atinux** [comment] 2016-11-18 17:31
@declandewet @lijiakof I had the same error with nuxt.js when using vue-meta, it's because of `jsnext`, it was fixed by importing vue-meta this way:
```js
import Meta from 'vue-meta/lib/vue-meta.js' // require the ES2015 lib
```

I believe it is because on the jsnext import (trough Webpack), Vue does not check the `module.default` here: https://github.com/vuejs/vue/blob/dev/dist/vue.common.js#L3220

**Comment by declandewet** [comment] 2016-11-18 17:33
Thanks @Atinux - I will look into a fix for this shortly

**Comment by achen224** [comment] 2016-11-18 17:37
Hey @declandewet  thx for reply.

my project base on vue2+vue-router+vuex with SSR bundle by webpack 2.0

i find some intristing...and everything ok... but maybe it's not good 
below is my change


**before :**

App.js
```
import Vue from 'vue'
import App from '../component/App.vue'
import router from '../router'
import store from '../store'
import { sync } from 'vuex-router-sync'
import * as filter from '../filter'
Object.keys(filter).forEach(key => {
  Vue.filter(key, filter[key])
})
const app = new Vue({
  router,
  store,
  ...App
})
sync(store, router)
export { app, router, store }
```

/router/index.js
```
import Vue from 'vue'
import Router from 'vue-router'
import Meta from 'vue-meta'
Vue.use(Router)
Vue.use(Meta)
export default new Router({
  mode: 'history',
  /* istanbul ignore next */
  scrollBehavior: () => ({ y: 0 }),
  routes: [
    { path: '/', component: Index },
    { path: '*', redirect: '/' }
  ]
})
```

**after:**

App.js
```
import Vue from 'vue'
import Meta from 'vue-meta'
Vue.use(Meta)
.
.
.
```

/router/index.js
```
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
.
.
.
```

**Comment by declandewet** [comment] 2016-11-18 17:40
Definitely a module resolution problem then - I'll investigate how the ES2015 build (https://github.com/declandewet/vue-meta/blob/7da1a5a72a75926eb431d5cebea30cdad6a715d9/package.json#L60) is compiled

thanks @achen224

**Comment by declandewet** [comment] 2016-11-18 17:41
For now, you can use this workaround:

```js
import Meta from 'vue-meta/lib/vue-meta.js' // require the ES2015 lib
```

**Comment by achen224** [comment] 2016-11-18 17:48
thanks @declandewet @Atinux

```
import Meta from 'vue-meta/lib/vue-meta.js' // require the ES2015 lib
```

is better solution for now

**Closed** 2016-11-23 05:27 UTC
Labels: bug
