### ISSUE TITLE
 Cannot convert undefined or null to object(…)

### ISSUE THREAD

**Issue by JosephSmith127** [declandewet/vue-meta#31] opened 2016-11-24 20:04 UTC
I have it setup with vue-router.

whenever I do the Vue.use(VueMeta); I get the current console error and it doesn't load my component.

`vue-meta.js?ffcf:1151Uncaught TypeError: Cannot convert undefined or null to object(…)`

**Comment by declandewet** [comment] 2016-11-24 22:03
Hi @JosephSmith127 - I have not run into this bug and have tests that indicate it works as it should, and I don't see any similar errors in [Nuxt.js](https://github.com/nuxt/nuxt.js), which uses `vue-meta`.

Could you help me out here and provide a little more info so I can try to reproduce this? Any of the following info (the more the better) will help:

- Node.js version
- `vue` version
- `vue-router` version
- using webpack? if so, what version?
- an example of what your `metaInfo` property config looks like in your component

**Comment by JosephSmith127** [comment] 2016-11-25 11:11
yeah sure, so its with the latest laravel build. 

Vue 2.0.1
VueRouter 2.0.3
and VueMeta 0.5.2

my node version is v6.9.1

and within my vue component of one of my routes I have put...


```
metaInfo() {
    	 	return {
    	 		title: 'Test title',
    	 	};
},
```

**Comment by declandewet** [comment] 2016-11-25 21:30
The only thing bothering me with your code sample is the trailing comma, but that's a matter of style. I'm not a PHP dev so it took me some time to set up a project that allowed me to replicate this bug you're reporting, but I can't seem to reproduce the issue. :/ It works for me.

I'll try to get some better error handling in before I release 1.0 that might outline a little better where these types of errors are coming from - that being said, `vue-meta`, while it does support client-side updates, was born out of a need for server-side rendering. That's the main focus. If you just want to manipulate the `title` on the client-side and/or don't care about server side use and this issue is blocking your progress on a client project, please have a look at any of the following alternatives to `vue-meta`:

- https://github.com/ktquez/vue-head
- https://github.com/miaolz123/vue-helmet
- https://github.com/egoist/head-tags

**Comment by imcvampire** [comment] 2016-12-22 08:37
There is a problem with this line https://github.com/declandewet/vue-meta/blob/master/src/shared/plugin.js#L31

`defaultOptions === undefined` when run in node

**Comment by imcvampire** [comment] 2016-12-22 15:06
I just created a MR to fix this https://github.com/declandewet/vue-meta/pull/39

**Comment by declandewet** [comment] 2016-12-23 14:16
Thanks for the insight @imcvampire. I will look into your PR ASAP.

**Comment by shyiko** [comment] 2017-01-10 07:06
Explanation (& jsfiddle example) in #47.

**Comment by Atinux** [comment] 2017-03-06 18:09
Fixed in the next release

**Closed by Atinux** 2017-03-06 18:09 UTC
